[project]
name = "03-airflow"
version = "0.1.0"
description = "iot data ingestion with airflow kafka hdfs and hive"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apache-airflow>=2.10.5",
    "pandas>=2.2.3",
]
