CREATE DATABASE metastore_db;

CREATE USER hive WITH PASSWORD 'password';

GRANT ALL PRIVILEGES ON DATABASE metastore_db TO hive;

\c metastore_db

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO hive;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO hive;

ALTER USER hive WITH SUPERUSER;
